#!/bin/bash

PATH="$target_directory/bin:$target_directory/sbin:$target_directory/usr/bin:$target_directory/usr/sbin:$PATH" \
/usr/bin/make -j5 \
  install_root=$staging_directory install \
  -C $build_directory/build/

for libs in ld*.so.* libanl.so.* libc.so.* libcrypt.so.* libdl.so.* \
    libgcc_s.so.* libm.so.* libnsl.so.* libpthread.so.* libresolv.so.* \
    librt.so.* libutil.so.* libnss_files.so.* libnss_dns.so.* libmvec.so.*; do \
  LIB="$libs"; \
  LIBPATHS=`find $staging_directory/ -name "${LIB}" 2>/dev/null` ; \
  for LIBPATH in ${LIBPATHS} ; do \
    DESTDIR=`echo ${LIBPATH} | sed "s,^$staging_directory/,," | xargs dirname` ; \
    mkdir -p $target_directory/${DESTDIR}; \
    while true ; do \
      LIBNAME=`basename ${LIBPATH}`; \
      LIBDIR=`dirname ${LIBPATH}` ; \
      LINKTARGET=`readlink ${LIBPATH}` ; \
      rm -fr $target_directory/${DESTDIR}/${LIBNAME}; \
      if test -h ${LIBPATH} ; then \
      	ln -sf `basename ${LINKTARGET}` $target_directory/${DESTDIR}/${LIBNAME} ; \
      elif test -f ${LIBPATH}; then \
      	/usr/bin/install -D -m0755 ${LIBPATH} $target_directory/${DESTDIR}/${LIBNAME}; \
      else \
      	exit -1; \
      fi; \
      if test -z "${LINKTARGET}" ; then \
      	break ; \
      fi ; \
      LIBPATH="`readlink -f ${LIBPATH}`"; \
    done; \
  done ; \
done
