#!/bin/bash

run_command "cd $build_directory/build"

PATH="$_PATH" \
PKG_CONFIG="/usr/bin/pkg-config" \
PKG_CONFIG_SYSROOT_DIR="/" \
PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 \
PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 \
PKG_CONFIG_LIBDIR="$staging_directory/usr/lib/pkgconfig:$staging_directory/usr/share/pkgconfig" \
LDFLAGS="-L$staging_directory/usr/lib" \
/usr/bin/make -j5 \
  gcc_cv_libc_provides_ssp=yes \
  all-gcc \
  all-target-libgcc \
  -C $build_directory/build
  