#!/bin/bash

package_fullname=gcc-final
package=gcc
version=6.3.0
package_source=$package-$version.tar.bz2
package_url=http://ftpmirror.gnu.org/$package/$package-$version/$package_source
host_package=yes
